apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-devops-copilot
  labels:
    app: ai-devops-copilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-devops-copilot
  template:
    metadata:
      labels:
        app: ai-devops-copilot
    spec:
      containers:
        - name: ai-devops-copilot
          image: dankbhardwaj/ai-devops-copilot:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_BASE_URL
              value: "http://host.docker.internal:11434"
          volumeMounts:
            - name: chroma-storage
              mountPath: /app/chroma_db
      volumes:
        - name: chroma-storage
          emptyDir: {}