name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: dankbhardwaj/ai-devops-copilot

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Update Deployment Image
        run: |
          kubectl set image deployment/ai-devops-copilot \
          ai-devops-copilot=$IMAGE_NAME:${{ github.sha }}

      - name: Verify Rollout
        run: kubectl rollout status deployment/ai-devops-copilot